### ISSUE TITLE
Articulos

### ISSUE THREAD

**Issue by matipretz** [matipretz/grupo9noticias#10]
Generar contenido variado para utilizar como mock de los articulos.
Titulo
Subtitulo/descripcion breve
Cuerpo de noticia
Una imagen

**Comment by matipretz** [comment]
Podria almacenarse en un JSON

**Comment by ojlucas** [comment]
ya cree la nota1.html, lineada desde la nota inicial de la home. dejamos para la segunda parte ir a cada nota desde el json, por ahora solo lo lee para llenar la página noticias
