### ISSUE TITLE
Revisar margenes de cards en Home

### ISSUE THREAD

**Issue by matipretz** [matipretz/grupo9noticias#31]
Las cards en home tienen un margen raro. Asimétrico

**Comment by ojlucas** [comment]
margen o tamaño asimétrico?

**Comment by matipretz** [comment]
![image](https://github.com/matipretz/grupo9noticias/assets/30426732/9ca927be-fc10-4a88-b7d2-e5430469ff31)

En el margen derecho de las cards, y el no habia visto tambien el divisor del nav

**Comment by ojlucas** [comment]
hay que poner un media query para la clase contenedor, 
en dispositivos chicos el valor de esa clase tiene que ser

.contenedor {
    grid-template-columns: repeat(auto-fit, minmax(100%, 1fr));
}

porque estaba seteado en px en lugar de %

**Comment by ojlucas** [comment]
ahora creo una rama y lo arreglo, dame unos minutos

**Comment by ojlucas** [comment]
ya subí la actualización

**Comment by matipretz** [comment]
Hay un problema con la imagen del centro. El texto animado queda cortado. Adjunto imagen.
Resolver o recortar texto

![image](https://github.com/matipretz/grupo9noticias/assets/30426732/777c386e-515b-4104-8430-98fae2bb158b)

**Comment by ojlucas** [comment]
el problema lo causa lg:mt-64, que le da un margin top fijo cuando el contenido puede ser variable. Hay que hacer un resumen más corto para mobile, sino se complica me parece meter un texto muy variable y que puede exceder el espacio
