### ISSUE TITLE
Notas del profesor en el excel de grupos

### ISSUE THREAD

**Issue by ojlucas** [matipretz/grupo9noticias#41]
recomendaría que las imágenes tengan todas el mismo tamaño, pueden usar propiedades css como object-fit o background-size (según corresponda) para resolver dicho problema. Recuerden que tienen que existir 4 html funcionando (como mínimo)

**Comment by ojlucas** [comment]
agregué

.group {
  height: 590px;
  overflow: hidden;
}

para fijar el tamaño de las imagenes que quedaban con un alto distinto, no encontré porque lo hacía, pero con esto lo dejé fijo

**Comment by matipretz** [comment]
Habria que cambiar la disposicion a columna con un media q para evitar que quede todo el texto apretado
