### ISSUE TITLE
Estilo submit

### ISSUE THREAD

**Issue by matipretz** [matipretz/grupo9noticias#62]
El estilo predeterminado del boton no se ve.
Puede que esté roto por culpa de tailwind

**Comment by ojlucas** [comment]
no veo que tenga una clase definida (ni ccs puro con tailwind), todos los resets que tiene reset.css hace que no tenga estilo, por eso se ve blanco sin nada
abria definirle un estilo propio al botón

**Comment by matipretz** [comment]
Tailwind tiene su propio reset y afecta al button.
La forma mas facil de verlo es quitar reset.css y el import de tailwind alternativamente.
Al quitar reset.css no hay cambios, y al quitar Tailwind vuelve a tener el estilo por defecto.
Al parecer tambien afecta a los estilos de los botones del footer. 
Aprovechando esto, le doy estilo con Tailwind y ya, pero es algo que habria que resolver de otra forma.

Gajes de importar todo tailwind y no poder configurarlo

**Comment by ojlucas** [comment]
ah, entonces era un issue retorico, y sin darme cuenta fui y los respondí :P

**Comment by matipretz** [comment]
Jajaja. No no, estuviste bien. A partir de tu respuesta me acorde de revisarlo y aproveche que tenia un ratito.
Le di estilo al boton para zafar. Cierro issue
